# Generated by Django 4.0.4 on 2022-05-05 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_especie', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Raza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_raza', models.CharField(max_length=50)),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donacion.especie')),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_mascota', models.CharField(max_length=50)),
                ('edad_mascota', models.IntegerField(default=0)),
                ('color', models.CharField(max_length=50)),
                ('fecha_registro', models.DateTimeField(verbose_name='Fecha de registro de mascota')),
                ('peso', models.IntegerField(default=0)),
                ('raza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donacion.raza')),
            ],
        ),
        migrations.CreateModel(
            name='Donacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_donacion', models.DateTimeField(verbose_name='fecha de donacion')),
                ('nombre_cliente', models.CharField(max_length=200)),
                ('dni', models.CharField(max_length=8)),
                ('edad', models.IntegerField()),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donacion.mascota')),
            ],
        ),
    ]
