# Generated by Django 4.0.4 on 2022-05-05 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='estado',
            field=models.IntegerField(default=0),
        ),
    ]
